name: Continuous Integration
on:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/**'
      - '**/*.md'

permissions:
  contents: write
  
jobs:
  build-and-push-docker:
    name: Build and Push Docker
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5001:5000
    env:
      TEST_TAG: localhost:5001/actions/env-output-setter:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 10

      - name: Configure Git Safe Directory
        run: git config --global --add safe.directory ${{ github.workspace }}

      - name: Setup Docker BuildX
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver-opts: network=host

      - name: Build the Container
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.TEST_TAG }}

      - name: Run the Container
        env:
          ENV_KEY: test1,test2
          ENV_VALUE: somaz,gomaz
          OUTPUT_KEY: test1,test2
          OUTPUT_VALUE: zomaz,xomae
        run: |
          docker run \
          --env ENV_KEY="${{ env.ENV_KEY }}" \
          --env ENV_VALUE="${{ env.ENV_VALUE }}" \
          --env OUTPUT_KEY="${{ env.OUTPUT_KEY }}" \
          --env OUTPUT_VALUE="${{ env.OUTPUT_VALUE }}" \
          --volume ${{ github.workspace }}:/app \
          --rm ${{ env.TEST_TAG }}

  test-action:
    name: Test env-output-setter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 10

      - name: Configure Git Safe Directory
        run: git config --global --add safe.directory ${{ github.workspace }}

      - name: Test Local Action
        id: set_variables
        uses: ./
        with:
          env_key: test1,test2
          env_value: somaz,gomaz
          output_key: test1,test2
          output_value: zomaz,xomae

      - name: Display Individual Environment Variables
        run: |
          echo "Displaying individual environment variables:"
          echo "test1: ${{ env.test1 }}"
          echo "test2: ${{ env.test2 }}"
          echo "TEST1: ${{ steps.set_variables.outputs.test1 }}"
          echo "TEST2: ${{ steps.set_variables.outputs.test2 }}"
