name: Continuous Integration
on: 
  workflow_dispatch: 
    inputs: 
      run: 
        description: 'workflow run' 
        required: true 
        default: 'true'
permissions: 
  contents: write
jobs: 
  build-and-push-docker: 
    name: Build and Push Docker 
    runs-on: ubuntu-latest 
    services: 
      registry: 
        image: registry:2 
        ports: 
          - 5001:5000
    env: 
      TEST_TAG: localhost:5001/actions/env-output-setter:latest
    steps: 
      - name: Checkout 
        uses: actions/checkout@v4 
        with: 
          fetch-depth: 10
      
      - name: Configure Git Safe Directory 
        run: git config --global --add safe.directory ${{ github.workspace }}
      
      - name: Setup Docker BuildX 
        uses: docker/setup-buildx-action@v3 
        with: 
          install: true 
          driver-opts: network=host
      
      - name: Build the Container 
        uses: docker/build-push-action@v6 
        with: 
          context: . 
          push: true 
          tags: ${{ env.TEST_TAG }}
      
      - name: Run the Container 
        id: run
        env: 
          ENV_KEY: test1,test2 
          ENV_VALUE: somaz,gomaz 
          OUTPUT_KEY: test1,test2 
          OUTPUT_VALUE: zomaz,xomae 
        run: | 
          docker run \
          --env ENV_KEY="${{ env.ENV_KEY }}" \
          --env ENV_VALUE="${{ env.ENV_VALUE }}" \
          --env OUTPUT_KEY="${{ env.OUTPUT_KEY }}" \
          --env OUTPUT_VALUE="${{ env.OUTPUT_VALUE }}" \
          --volume ${{ github.workspace }}:/app \
          --rm ${{ env.TEST_TAG }} 

      - name: Display Individual Environment Variables
        run: |
          echo "Displaying individual environment variables:"
          echo "test1: {{ env.test1 }}"
          echo "test2: ${{ env.test2 }}"

      - name: Display Success Message
        run: |
          echo "Success: ${{ steps.set_variables.outputs.success_message }}"
  
    outputs:
      TEST1: ${{ steps.run.outputs.test1 }}
      TEST2: ${{ steps.run.outputs.test2 }}
